### PR TITLE
Debugger improvements

### LINKED ISSUE #26: Make log level an cli option
Currently the log level depends on the compile mode:
- develop/debug will display all messages
- release will display only error messages

This should be controllable via a cli option.

### LINKED ISSUE #27: Make app compatible with Windows
Currently the build process fails because of cursive dependancy. This should only be used, if we build on a supported platform.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
- Log and ASM views are now scrollable
- ASM view will cache decoded instructions to show instructions before PC
- Views are updated only when necessary, which should reduce CPU usage
- Better structure

CC #18 
Closes #26 
Closes #27

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
I couldn't keep myself from implementing more stuff. Most importantly:

- Fix quite a few PPU bugs (I know, this has nothing to do with the debugger, sorry for non-atomic PRs :P)
- Add box showing (almost) all PPU register (in a second right panel)
- Reduce CPU usage when debugger is paused
- You can now view, set and unset breakpoints by clicking in the ASM view

But I'm gonna stop now. So this PR is ready.

File: core/src/machine/ppu.rs [hunk 1]
```diff
@@ -249,14 +309,21 @@ impl Ppu {
...
                 (20..144, col) if col < 160 => {
+                    if self.cycle_in_line == 20 {
+                        self.set_phase(Phase::PixelTransfer);
+                    }
                     self.pixel_transfer_step(display);
                 }
-                (43..144, _) => {
-                    // TODO: H-Blank
-                    // debug!("[ppu] hblank. current_line: {}", self.current_line);
+                (43..144, col) if self.phase() == Phase::HBlank && col == 160 => {
```
Comment (jovobe) [inline core/src/machine/ppu.rs]: Use `SCREEN_WIDTH` instead of magic number `160`.

File: core/src/machine/ppu.rs [hunk 2]
```diff
@@ -290,6 +357,13 @@ impl Ppu {
         while self.fifo.len() > 8 && pixel_pushed < 4 {
             self.push_pixel(display);
             pixel_pushed += 1;
+
+            // We we are at the end of the line, stop everything and go to
```
Comment (jovobe) [inline core/src/machine/ppu.rs]: The "we" cloned itself 😱

File: core/src/machine/ppu.rs [hunk 3]
```diff
@@ -290,6 +357,13 @@ impl Ppu {
...
+            // H-Blank.
+            if self.current_column == 160 {
```
Comment (jovobe) [inline core/src/machine/ppu.rs]: Use `SCREEN_WIDTH` instead of magic number `160`.

**Review by jovobe — CHANGES_REQUESTED** [review]

**Comment by LukasKalbertodt** [comment]
I, again, worked on this instead of doing other stuff 😩

image

I guess these generated comments could come handy.

Other changes include log level via CLI and performance improvements.

File: core/src/machine/ppu.rs [hunk 4]
```diff
@@ -184,20 +193,30 @@ impl Ppu {
...
-            0xFF40 => self.lcd_control = byte,
+            0xFF40 => {
+                let was_enabled = self.lcd_enabled();
+                self.lcd_control = byte;
+                match (was_enabled, self.lcd_enabled()) {
+                    (false, true) => {
+                        info!("[ppu] LCD was enabled");
+                        self.set_phase(Phase::OamSearch);
+                        self.cycle_in_line = 0;
+                        // TODO: also reset other stuff?
```
Comment (jovobe) [inline core/src/machine/ppu.rs:204]: Do we need to reset the current line here too? (e.g. `self.current_line = Byte::new(0);`)

**Review by jovobe — CHANGES_REQUESTED** [review]

File: core/src/machine/ppu.rs (hunk 4 above)
Comment (LukasKalbertodt) [reply core/src/machine/ppu.rs:204]: I don't think so. The current line is set to 0 a few lines below, when the LCD is disabled. I actually think that most things should be "reset" when the LCD is disabled instead of when it is enabled. 

I think the TODO is a bit outdated. But it might still be useful until we figured this out.

**Review by jovobe — APPROVED** [review]

**Comment by jovobe** [comment]
I ignored everything in `desktop/src/debug` for the review.
